### ISSUE TITLE
collectie DIVA geeft 0 items

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#51]
assigned @JorisLambrechts 
browsen op de collectie diva geeft 0 items. In de admin staan er nochtant 6 items in deze collectie gepubliceerd 

![capture](https://cloud.githubusercontent.com/assets/3798589/16150832/ed9a508a-3499-11e6-8a8e-7346dd015740.JPG)

**Comment by JorisLambrechts** [comment]
de items waren nog niet geindexeerd, nu verschijnen ze wel
