### ISSUE TITLE
wijzigingen images in Omeka van test naar productie zetten

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#53]
De wijzigingen mogen overgezet worden naar de productie:
upload map voor images aanmaken
upload size voor images vergroten
regel toevoegen om Omeka images te tonen indien geen rosetta images beschikbaar zijn
titel tonen bij mouse over thumbnial

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Flandrica/commit/ff965890031699ef082eb828256b5e5b5b1ee360
https://github.com/libis/Flandrica/commit/0c60142ba8c14aa7d3397a00a34cd1250cf1b8c7
map 'upload' aangemaakt via image manager
upload size aangepast in htaccess
