### ISSUE TITLE
HTML in Afbeelding titel niet weergegeven

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#54]
HTML in titles komt er niet altijd goed door. Nochtans aangevinkt in record. Ook na opnieuw aanvinken en saven geen verandering.
![capture](https://cloud.githubusercontent.com/assets/3798589/17218166/2337e884-54e7-11e6-8c26-f50d44d42481.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/17218210/4d340320-54e7-11e6-87ae-027e94ad2bb9.JPG)

**Comment by roxannewyns** [comment]
Kan je eens kijken of dit kan? Indien niet zal ik nieuwe instructies geven aan Flandrica rond het gebruik van html in de titels.

**Comment by JorisLambrechts** [comment]
De titel die je ziet is het alt-attribuut van een img-tag en daar mag geen html in zitten. Ik zal de html-tags dus uit de titel filteren voor de thumbnail-gallery
