### ISSUE TITLE
hoe plaats toevoegen op kaart

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#57]
De waarde in creatieplaats moet om de kaart worden toegevoegd. Hoe doe ik dit automatisch (bij import?) voor Flandrica? Zoeken op een plaats lukt trouwens ook geval niet.

**Comment by JorisLambrechts** [comment]
Dat lukt standaard niet, dat moet apart opgezet worden. We kunnen wel de coördinaten gewoon als metadata mee importeren en daarna een scriptje laten lopen dat dan de locatie-tabel update.

Voor versie 2.x is er wel een aangepaste csv-import-plugin waarmee je locaties kan importeren
