### ISSUE TITLE
sorteervolgorde items aanpassen op laatst toegevoegde

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#58]
De meest recent toegevoegde items zouden bovenaan moeten staan in de sortering van de zoekresultaten / collectielijst /solr-search/results/?solrfacet=collection:"Museum Plantin-Moretus" . 

Kan je dit aanpassen?

**Comment by JorisLambrechts** [comment]
Ik vrees dat dat niet mogelijk is. De solr-functionaliteiten om te sorteren zijn al beperkt door de multivalue-velden en deze zitten dan nog niet eens in de solr-plugin voor omeka.

**Comment by roxannewyns** [comment]
Een terugkerend probleem. Is sorteren op record ID nummer misschien mogelijk? Bv. /items/show/1531/ /items/show/1530/, /items/show/1529/

Valt zoiets te ontwikkelen of niet?

**Comment by roxannewyns** [comment]
Dit kan een andere oplossing zijn voor Flandrica http://omeka.org/codex/Plugins/ItemOrder_2.0 
Misschien kan je de plugin eens installeren om te zien wat het geeft. Er is een plugin die werkt met versie 1.5
