### ISSUE TITLE
downloadbaar maken van opgeladen afbeeldingen

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#59]
De Flandrica partner zou graag de opgeladen afbeeldingen kunnen downloaden.
Je kan in de Omeka back-end op de afbeeldingen klikken om ze te downloaden denk ik. Je krijgt dan wel een foutmelding.

**Comment by JorisLambrechts** [comment]
downloaden lukt bij mij zonder problemen (rechtsklik en save), of bedoel ik je iets anders?

**Comment by roxannewyns** [comment]
dan download je de jpg afgeleide, althans bij mijn poging. Ze willen de jpg2 of tif kunnen downloaden

**Comment by roxannewyns** [comment]
Gewone JPEGs zijn geen probleem. JPG2 geeft een foutmelding (e.g. object 1729) "Zend_Controller_Dispatcher_Exception. Invalid controller specified (archive)". 
Mogelijk omdat Omeka hier geen viewer voor heeft. echtermuisklik 'save as' gaat ook niet. Andere suggestie?

**Comment by JorisLambrechts** [comment]
het was een htaccess-probleem, heb jp2 en tif toegevoegd in de htaccess rewrite rules

lijn 28: `RewriteRule !\.(js|ico|gif|jpg|png|jp2|tif|css)$ index.php`
