### ISSUE TITLE
JPEG2 niet zichtbaar in back-end

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#60]
Bij TIFF files worden de afbeeldingen getoond in de back-end, maar bij JPEG2 krijg je enkel links te zien. 
Het is maar een detail, maar is het mogelijk om die ook te tonen?

**Comment by JorisLambrechts** [comment]
De meeste browsers kunnen dat niet lezen, je hebt daar dus eigenlijk een extra viewer voor nodig. Omeka support jpeg2 dus eigenlijk niet, je kan ze wel inladen maar verder gebeurt er niets mee.
