### ISSUE TITLE
Plaatsen buiten europa tonen niet allemaal op de kaart

### ISSUE THREAD

**Issue by roxannewyns** [libis/Flandrica#61]
Plaatsen buiten europa tonen niet allemaal op de kaart (e.g. USA, China).

Bv. Item /items/show/626/ heeft als Creatieplaats "China", maar staat niet op de kaart. 

Er staat wel 1 item op de kaart voor Beijing. Misschien is gewoon de mapping op basis van plaatsnaam niet gelukt?

**Comment by JorisLambrechts** [comment]
ik had een workaround in de code gezet om identieke coördinaten toch als aparte labels op de kaart te krijgen maar daardoor gingen er blijkbaar een aantal locaties verloren. Ik heb de workaround nu weggehaald en in de plaats de plugin geactiveerd die we ook bij cag gebruiken om indentieke coördinaten te tonen. China en dergelijke verschijnen nu wel op de kaart.
